# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parroter.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "parroter.ParrotRequest" do
    optional :msg, :string, 1
  end
  add_message "parroter.ParrotResponse" do
    optional :msg, :string, 1
    optional :count, :int32, 2
  end
end

module Parroter
  ParrotRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("parroter.ParrotRequest").msgclass
  ParrotResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("parroter.ParrotResponse").msgclass
end
