# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: parroter.proto for package 'parroter'

require 'grpc'
require 'parroter_pb'

module Parroter
  module ParrotService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'parroter.ParrotService'

      rpc :say, ParrotRequest, ParrotResponse
    end

    Stub = Service.rpc_stub_class
  end
end
